spring.application.name=subscription-service
server.port=8080

# Conexión a la BBDD (Asumiendo que usas spring-dotenv como vimos antes)
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Estrategia de JPA: "update" crea las tablas si no existen, y las actualiza si hay cambios. No borra datos.
spring.jpa.hibernate.ddl-auto=update

# Opcional pero súper útil: Para ver en la consola el SQL que Spring genera por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect